#! /bin/sh

jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode

# jupyter serverextension enable --py jupyter_archive

jupyter nbextension install --py jupyter_notebookparams --sys-prefix
jupyter nbextension enable --py jupyter_notebookparams --sys-prefix

jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install @jupyterlab/server-proxy --no-build

jupyter lab build

sed -i 's/\#!\/srv\/conda\/envs\/notebook\/bin\/python/\#!\/usr\/bin\/python3/'  /srv/conda/envs/notebook/bin/unoconv
