[tool.nbqa.addopts]
flake8 = [
    "--ignore=E501,W503,E203"
]
[tool.isort]
profile = "black"
[tool.pytest.ini_options]
addopts = "--ignore-glob=Untitled* --ignore-glob=getting-started* --ignore=snippets.ipynb --ignore=newspaper-explorer.ipynb --ignore-glob=App* --ignore-glob=draft* --ignore=appmode-checking.ipynb"